name: Docker Image CI

on:
  push:
    branches: "*"
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        if: github.ref_name == 'master'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Build the images
        if: github.ref_name != 'master'
        run: ./scripts/build.sh "${{ matrix.python_version }}"

      - name: Build and push the images
        if: github.ref_name == 'master'
        run: ./scripts/build.sh "${{ matrix.python_version }}" --push
